### ISSUE TITLE
Cannot compile stock_reconcialiation_per_item_group.py

### ISSUE THREAD

**Issue by redolencetech** [scopen-coop/stock_reconcialiation_per_item_group#1]
I'm getting a compile error for stock_reconcialiation_per_item_group.py for inconsistent tabs and spaces

<img width="906" alt="image" src="https://user-images.githubusercontent.com/6630615/236391386-3e88be05-bebc-48b7-ad3e-bbc08dfc4acd.png">

**Comment by FHenry** [comment]
@redolencetech 
How do you do ?
When the bench update ?

**Comment by FHenry** [comment]
I use the same pre-commit (https://github.com/frappe/erpnext/blob/version-14/.pre-commit-config.yaml) feature the the one use in ERPNext to keep the product standard, but I see that it exclude W191 and E101....

How do you do on your side ?

**Comment by redolencetech** [comment]
Just checked, I wasn't using the version-14 branch, was using main - it worked after switching across. Thanks!
